spring.application.name=backend

# Here its set to store data in file, for persistence of test users
#TODO: Remember to remove the datasource fallback defaults, after deployment
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/mindmeshdb}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${DB_ADMIN_USERNAME:sa}
spring.datasource.password=${DB_ADMIN_PASSWORD:}

# JPA settings
# ddl-auto set to update, to automatically modify the schema to fit future entities
# More deployment convenience. BETTER DISABLE later
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# enable console, viewed in browser through /h2-console endpoint
# Remember that spring security blocks this by default, need to allow /h2-console/ in SecurityConfig
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=${JWT_SECRET:sfTv/7R8If5Co9pmetKOuRXj5a94mxtdvKmUn6d76VLTosAN9DucEXWn9a+JKgmHS3ms4JSB7E1KMT7IEBsjlg==}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

# CORS
frontend.url=${FRONTEND_URL:http://localhost:5173}
